amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accessKey: testcraftdemo
    secretKey: testcraft
    region: localhost
spring:
    data:
      dynamodb:
        entity2ddl:
          auto: create
product-subscription:
  quickbooks: "/v1/quickbooks/validate"
  qbpayroll: "/v1/qbpayroll/validate"
  qbpayments: "/v1/qbpayments/validate"
  tsheets:  "/v1/tsheets/validate"

