package com.demo.craftdemo.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.util.*

@DynamoDBTable(tableName = "product")
data class Product(

    @DynamoDBHashKey(attributeName = "product_id")
    @DynamoDBAutoGeneratedKey
    var productId: UUID? = null,

    @DynamoDBAttribute(attributeName = "product_name")
    var productName: String? = null

)
