package com.demo.craftdemo.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.util.UUID

@DynamoDBTable(tableName = "subscription")
data class Subscription(

        @DynamoDBHashKey(attributeName = "subscription_id")
        @DynamoDBAutoGeneratedKey
        var id: UUID? = null,

        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        @DynamoDBAttribute(attributeName = "product_id")
        var productId: UUID? = null,

        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        @DynamoDBAttribute(attributeName = "user_id")
        var userId: UUID? = null

)
