package com.demo.craftdemo.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import lombok.Data
import java.util.*

@Data
@DynamoDBTable(tableName = "subscriber")
data class Subscriber (

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    val userId: UUID? = null,


    @DynamoDBAttribute(attributeName = "company", mappedBy = "company")
    private var company: String? = null,


)