package com.demo.craftdemo.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.util.*

@DynamoDBTable(tableName = "user_profile")
class UserProfile (

    @DynamoDBHashKey(attributeName = "user_profile_id")
    @DynamoDBAutoGeneratedKey
    var userProfileId: UUID? = null,

    @DynamoDBAttribute(attributeName = "company_name")
    private var companyName: String? = null,

    @DynamoDBAttribute(attributeName = "legal_name")
    private var legalName: String? = null,

    @DynamoDBAttribute(attributeName = "business_address")
    private var businessAddress: Address? = null,

    @DynamoDBAttribute(attributeName = "legal_address")
    private var legalAddress: Address? = null,

    @DynamoDBAttribute(attributeName = "tax_identifier")
    private var taxIdentifier: String? = null,

    @DynamoDBAttribute(attributeName = "email")
    private var email: String? = null,

    @DynamoDBAttribute(attributeName = "website")
    private var website: String? = null,

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "user_id")
    var userId: UUID? = null

) {
    fun setEmail(email: String){
        this.email = email
    }

    fun setLegalAddress(address: Address){
        this.legalAddress = address
    }

    fun setBusinessAddress(address: Address){
        this.businessAddress = address
    }

    fun setCompanyName(companyName: String){
        this.companyName =  companyName
    }

    fun setLegalName(legalName: String){
        this.legalName = legalName
    }

    fun setTaxIdentifier(taxId: String){
        this.taxIdentifier = taxId
    }

    fun setWebsite(website: String){
        this.website = website
    }

    fun getEmail() = this.email

    fun getLegalAddress() = this.legalAddress

    fun getBusinessAddress() = this.businessAddress

    fun getCompanyName() = this.companyName

    fun getLegalName() = this.legalName

    fun getTaxIdentifier() = this.taxIdentifier


    fun getWebsite() = this.website

}